### ISSUE TITLE
Special case 0 or 1?

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/javascript-intro-to-looping#14]
The test says it's looking for:

"I am ${i} strange loop${i === 0 ? '' : 's'}."

But shouldn't it be looking for

"I am ${i} strange loop${i === 1 ? '' : 's'}."

?

**Comment by AnnJohn** [comment]
hi @jonbf could you please use Ask a Question and someone will help you out right away. Thanks!

**Comment by jonbf** [comment]
For sure - I shouldn't have phrased the comment as a question -- I meant it
not for my own benefit but as a suggested diff to the curriculum. Of course
I am a n00b and the suggestion may be wrong :)
