### ISSUE TITLE
Function def'n in error message

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/javascript-intro-to-looping#15]
Should the following error message: 

loops doWhile(array) removes elements from `array` until `array` is empty or until `maybeTrue()` returns `false`:

instead say:

loops doWhileLoop(array) removes elements from `array` until `array` is empty or until `maybeTrue()` returns `false`:

**Comment by AnnJohn** [comment]
hi @jonbf please use Ask a Question and someone from our team will help you out right away. thanks!
