### ISSUE TITLE
Javascript Intro To Looping - THE DO-WHILE LOOP

### ISSUE THREAD

**Issue by srb4887** [learn-co-curriculum/javascript-intro-to-looping#17]
The directions say "TODO: Define a function called doWhile in loops.js." but that returns the error "ReferenceError: doWhileLoop is not defined"

**Comment by AnnJohn** [comment]
thanks for raising, and yes that'a  typo on our end. It should be "Define a function called doWhileLoop" and we'll update it. Thanks for raising!

**Comment by Sbartra** [comment]
I am having problems with the function doWhileLoop is not working.
