### ISSUE TITLE
The third test calls the wrong function so it won't pass unless the student changes it.

### ISSUE THREAD

**Issue by pickledyamsman** [learn-co-curriculum/javascript-intro-to-looping#18]
This is in the bootcamp prep branch.

On line 57 of test/loops-test.js,
    describe('doWhile(array)', () => { 
should be replaced by 
    describe('doWhileLoop(array)', () => { 
to validate with what it is testing against.

This was an open issue on learn-co-students and has stopped some students from progressing in the track.

**Comment by pickledyamsman** [comment]
@aturkewi @AnnJohn

**Comment by aturkewi** [comment]
Thanks @pickledyamsman Fixed it with PR #19
