### ISSUE TITLE
Incorrect function naming in test

### ISSUE THREAD

**Issue by TinaHeiligers** [learn-co-curriculum/javascript-intro-to-looping#24]
In the test for the do-while loop function, the newArray is called by invoking the function doWhileLoop(array). This throws an error of doWhileLoop is undefined.
I had to change line 62 in the test from:
const newArray = doWhileLoop(array)
to:
const newArray = doWhile(array)
to get the test to pass.

**Comment by aturkewi** [comment]
Hey Tina! Thanks for raising this issue. Just fixed it with a couple of PRs #21 and #23

**Comment by TinaHeiligers** [comment]
Hey Avidor, thanks for letting me know in person!
I’m only to happy to contribute where I can, however small it might be.
Regards,
Tina
