### ISSUE TITLE
doWhile test

### ISSUE THREAD

**Issue by B-Dubs-23** [learn-co-curriculum/javascript-intro-to-looping#25]
Not sure if this was intentional or not, but for this exercise the Learn To Do instructions request to create a function called doWhile(), however the test is looking for a function called doWhileLoop(). I was stuck on this for a decent amount of time only to realize i needed to rename my function based off of the loops-test.js script. if this was intentional, kudos, because i struggled. if not, this could save other members from some struggle

**Comment by kwebster2** [comment]
This issue has been fixed on learn-co-curriculum, and learn-co-students for full stack and js-intro tracks, but it has not yet been fixed in the bootcamp-prep track @aturkewi

**Comment by aturkewi** [comment]
Fixed the deploy. It should be all set now! Thanks for the catching this :)
