### ISSUE TITLE
Passing with Loops "before all" hook message

### ISSUE THREAD

**Issue by Sirjustin** [learn-co-curriculum/javascript-intro-to-looping#31]
Hi! 

I just passed the test when I was trying to figure out what else I need to do.   I couldn't have passed the test so it must be a bug.   
![image](https://cloud.githubusercontent.com/assets/12264222/24123953/ffa725fa-0d97-11e7-9e62-8fd184ba2125.png)

**Comment by JessRudder** [comment]
@Sirjustin  please reach out to Learn Experts using "Ask a Question" in Learn if you are still having this issue.  They will help you debug it in real time.
