### ISSUE TITLE
My test passes even though it has an error

### ISSUE THREAD

**Issue by alanthinks** [learn-co-curriculum/javascript-intro-to-looping#32]
**This is what I'm asked for:**

"TODO: Define a function called doWhileLoop in loops.js. The function should take an array as an argument. Use the maybeTrue() function (you can copy it from this README) as the condition, and remove elements from the array until the array is empty or until maybeTrue() returns false. (Your condition might look something like `array.length > 0 && maybeTrue().)` Finally, return the array."

**Here's the code I typed which passed, even though `length` is misspelled, and it's not even `=== 0` which is what I think could be correct?**

```
function doWhileLoop(arr){
  function maybeTrue() {
  return Math.random() >= 0.5
}
  do {
    arr.pop()
  } while ((arr.leth==20) || !maybeTrue() )

return arr
}
```

**Comment by drakeltheryuujin** [comment]
Thank you for your contribution! We're rewriting this particular example and test. 💙
