### ISSUE TITLE
loops-test.js and instructions don't match for whileLoop(n)

### ISSUE THREAD

**Issue by dwiehoff** [learn-co-curriculum/javascript-intro-to-looping#34]
"count down from the passed in number to 0":
if the passed in number is 3 this should lead to:
3, 2, 1, 0 (four console logs)
The testing, however, requires that it be only three logs.

**Comment by drakeltheryuujin** [comment]
Hi there,

It looks like this may have been resolved. If not, please reopen the issue and I'll take another look.

Thanks for contributing!
