### ISSUE TITLE
Badly worded instructions:

### ISSUE THREAD

**Issue by baschenbrenner** [learn-co-curriculum/javascript-intro-to-looping#37]
TODO: Build a function forLoop. It takes an array as an argument. Start counting from 0, and, using a for loop, add a string to the array. But not just any string. If your i value is 1, add the string "I am 1 strange loop."; **but if your i value is anything else, add the string "I am ${i} strange loops." to the array 25 times.** (Remember flow control with if and else? And how do we interpolate i?) Then return the array.

 but if your i value is anything else, add the string "I am ${i} strange loops." to the array 25 times. 

I suggest: "but if your i value is anything else, add the string "I am ${i} strange loops." to your array. You should let your counter run 25 times."

**Comment by gj** [comment]
Fixed in #38. Thanks @baschenbrenner !
