### ISSUE TITLE
Bootcamp prep url missing to fork lab

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/javascript-intro-to-looping#39]
If you navigate to github.com/learn-co-students/javascript-intro-to-looping-bootcamp-prep-000 it gets 404'd. We have had a student pretty upset because they were able to get an older lab and they completed it, however the browser doesn't recognize that they completed it. I believe it was the older fork with `-batch` that they had forked and cloned.

Just thought i'd bring this up so that it could be fixed in case any other student gets the same issue.

**Comment by nikymorg** [comment]
Thanks for bringing this to our attention. We've fixed it so github.com/learn-co-students/javascript-intro-to-looping-bootcamp-prep-000 works now, but feel free to let us know if you see other issues around this.
