### ISSUE TITLE
doWhileLoop confusion

### ISSUE THREAD

**Issue by mrbaker1917** [learn-co-curriculum/javascript-intro-to-looping#44]
I think there is a confusing passage in the doWhileLoop TODO instructions:
Use the maybeTrue() function (you can copy it from this README) as the condition, and remove elements from the array until the array is empty or until maybeTrue() returns false. (Your condition might look something like array.length > 0 && maybeTrue().)
Because the instructions stipulate the conditions are this OR that, it is confusing that in the example the && is used. Is this deliberate? Would not || make more sense?

**Comment by drakeltheryuujin** [comment]
Updated. Thanks for you feedback! 💙
