### ISSUE TITLE
'learn test' faulty

### ISSUE THREAD

**Issue by Goofyrulz** [learn-co-curriculum/javascript-intro-to-looping#53]
While running 'learn test' I am not getting any identifier on what i am missing.  only total right wrong.  currently at 1 right and 2 wrong but i do not know what i am missing as the dialogue does not display errors from testing.

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE, ruby, npm, and node versions), I'd be happy to take a second look!

As always, thanks for contributing! 💙
