### ISSUE TITLE
Updated directions need revision 

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/javascript-intro-to-looping#55]
@drakeltheryuujin 
The updated directions for the `doWhileLoop` are unclear.  

The `incrementVariable` function should not be used as a condition, as it will always return `true`, since all it does is increment the value of a variable.  Additionally, the way it is used in the previous example in the README is not particularly relevant to the `doWhileLoop` function, since we are removing elements from an array (and using it correctly in this context would be pretty counterintuitive).

**Comment by justbennett** [comment]
A previous version has `maybeTrue` in place of `incrementVariable`. Maybe someone accidentally replaced too many `maybeTrue`s with `incrementVariable`s.

**Comment by sgharms** [comment]
I think this was addressed by https://github.com/learn-co-curriculum/javascript-intro-to-looping/commit/f315abd86f9699fbacce6d5833980037576364f9, could you verify @kwebster2 ?

**Comment by lizbur10** [comment]
Hi there! I'm closing this issue as the problem was addressed.
