### ISSUE TITLE
Javascript Intro to Looping - DoWhile Loop TODO - IncrementVariable

### ISSUE THREAD

**Issue by Robertoabr** [learn-co-curriculum/javascript-intro-to-looping#57]
In the intro to looping, it asks for the following:

TODO: Define a function called doWhileLoop in loops.js. The function should take an array as an argument. Use the incrementVariable() function (you can copy it from this README) as the condition, and remove elements from the array until the array is empty or until incrementVariable() returns false. (Your condition might look something like array.length > 0 && incrementVariable().) Finally, return the array.

incrementVariable() is defined in the lab as:
var i = 0;
 function incrementVariable() {
  i = i + 1;
}

IncrementVariable() will never evaluate to false?

Not sure what they are trying to teach by adding the complication of using this function, but clearly there is a typo or bad wording here. 

And the test doesn't catch it , since I mostly ignored the incrementVariable() and still passed the test.

-Roberto

**Comment by sgharms** [comment]
Fixed by our latest merge. Thanks!
