### ISSUE TITLE
doWhileLoop instructions need revision

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/javascript-intro-to-looping#61]
(Update: nevermind I just saw that this lab has been revised. For some reason the github link was going to the old one...)

The answer can not be reasonably deduced because the directions are flawed. 

"TODO: Define a function called doWhileLoop in loops.js. The function should take an integer as an argument. Use the incrementVariable() function (you can copy it from this README) in the condition, and console log "I run once regardless." while incrementVariable() returns a number less than the parameter received. (Your condition might look something like incrementVariable() < num.) Remember that it should also console log when receiving 0 as a parameter because the do-while runs before the condition is checked."

However, the test passed the function an *array* as an argument, NOT an integer. Following the directions will thus lead students astray and produce confusion. Please kindly fix this!

**Comment by Orod23** [comment]
is there anyway you can show your code for this specific problem i keep getting 2 passing and 2 failing.

**Comment by kpneylon** [comment]
me as well, not sure why this One is holding me up

**Comment by lizbur10** [comment]
Hi there! I'm closing this issue as the problem has been addressed :)
