### ISSUE TITLE
"Learn test" faulty

### ISSUE THREAD

**Issue by tommaclean** [learn-co-curriculum/javascript-intro-to-looping#62]
Hi, 

When I try to use "learn test" to test my code I am met with no response in the IDE. I have tried to refresh the page, clear my history/cookies, quitting Chrome but no luck. I am 3 sections from finishing the material I need for the technical interview. What can I do to fix this issue? 

Thanks

**Comment by maxwellbenton** [comment]
Hi @tommaclean,

Sorry to hear that you were experiencing issues getting the tests to run in the Learn IDE. Unfortunately, I am unable to replicate this issue but can confirm that this lesson is currently working as intended. If you are still working on any Learn lessons and continue to experience this issue, please feel free to reach out to support@learn.co for further assistance.

Thank you!
