### ISSUE TITLE
IDE Console Issue

### ISSUE THREAD

**Issue by LightbulbMG** [learn-co-curriculum/javascript-intro-to-looping#65]
The Learn IDE console has been giving me many problems with coding activities. It is so difficult to know what I am doing right or wrong when I get back responses that do not reflect any of my input or no response at all.

I am unable to test my code for this activity, I am not sure if I have done it correctly.

**Comment by maxwellbenton** [comment]
Hi @LightbulbMG,

Sorry to hear you were having difficulty getting the Learn IDE to work. Unfortunately, I am unable to replicate this issue but can confirm that this lesson is currently working as expected and producing accurate test results.

If you are still working on any Learn content and experiencing these issues, please reach out to support@learn.co for further assistance.

Thank you!
