### ISSUE TITLE
My first test has error with test-loops.js despite working function

### ISSUE THREAD

**Issue by aneme1038** [learn-co-curriculum/javascript-intro-to-looping#66]
My first test in the lab asked me to write a function that adds to an array 25 times on a loop. My function was written as follows:
```function forLoop(array){
  var number = ["I am a strange loop"];
  for (var i = 1; i < 25; i++){
  if (i === 1){ 
    number.push("I am 1 strange loop")
  } else {
    number.push(`"I am ${i} strange loops."`)
    }
  console.log(number);
  }
}
```
This function does indeed do exactly what the lab supposedly asks for however there is a TypeError.

It reads: 

TypeError: Cannot read property 'slice' of undefined
      at Context.it (test/loops-test.js:33:38)

The block of code related to this that I found in the test/loops-test.js:33;38 section is as follows:

```
describe('forLoop(array)', () => {
    it('adds `"I am ${i} strange loop${i === 0 ? \'\' : \'s\'}."` to an array 25 times', () => {
      const [array, t] = makeArray()
      const strangeArray = forLoop(array)
      const testArray = strangeArray.slice(array.length)**

      let first = "I am 1 strange loop."
      let rest = "I am 24 strange loops."

      expect(strangeArray[11]).to.equal(first)
      expect(strangeArray[34]).to.equal(rest)
      expect(strangeArray.length).to.equal(t + 25)
    })
  })
```
I cannot pass the lab without this error being addressed. I will attempt to figure out the issue but wanted to submit this issue as well.

**Comment by andrew-lewell** [comment]
Not sure if you figured this out yet but I think you need your 'console.log(number);' outside of the For loop.

**Comment by curchadw** [comment]
This still an issue with this. It gives me messages saying `1) loops
       forLoop(array)
         adds `"I am ${i} strange loop${i === 0 ? '' : 's'}."` to an array 25 times:
     ReferenceError: forLoop is not defined
      at Context.it (test/loops-test.js:32:28)`

even though I sat there and made the function

**Comment by curchadw** [comment]
Now I'm getting the same issue as you. 
`function forLoop(array){
  
  for(let i = 0; i < 25; i++){
      if(i === 1){
        console.log(`"I am ${i} strange loop."`)
      }else{
        console.log( `"I am ${i} strange loop${i === 0 ? '' : 's'}."`)
      }
     
    }
    

  
}`

**Comment by lizbur10** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
