### ISSUE TITLE
A Little confused

### ISSUE THREAD

**Issue by RefinedSilver** [learn-co-curriculum/javascript-intro-to-looping#72]
Hello, 

According to the solutions checklist I was able to solve the three TODOs for the "Javascript Intro To Looping" challenges. However, there was a prompt stating that I did not finish the assignments on that page
![2020-02-27 (10)](https://user-images.githubusercontent.com/38686254/75456596-ba84bc80-5948-11ea-8229-74358a03b794.png)
![2020-02-27 (9)](https://user-images.githubusercontent.com/38686254/75456662-cd978c80-5948-11ea-8505-0d1746ae0c56.png)

Here is my code for anyone's perusal:

function forLoop (a = []) {

  for (let i = 0; i < 25; i++) {
    if (i === 1) {
      a.push(`I am ${i} strange loop.`);
    } else {
      a.push(`I am ${i} strange loops.`);
    }
  }
  return a;
}
forLoop();

function whileLoop(n) {
  let countdown = n;

    while (countdown > 0) {
      console.log(--countdown);
    }
  return "done";
}
whileLoop();

function doWhileLoop(num) {
  let i = 0;

  do {
    function incrementVariable() {
      i = i + 1;
      return i;

    }
    console.log(`I run once regardless.`);
  } while (incrementVariable() < num);
}
doWhileLoop();

What needs to be changed as I am not entirely sure. Any response would be greatly appreciated. Thanks.

Ian

**Comment by lizbur10** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
