### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by detinsley1s** [learn-co-curriculum/javascript-intro-to-looping#73]
At the beginning of the page, under the first logging result within the Introduction section, the word "repetitive" is misspelled in the sentence "This works, but it is very repetative." This should be fixed so that it is spelled correctly.

In addition, the next sentence also has a typo. It misspells the word "it's" as "its." Since in this context the word is meant to be the contraction of "it is," "it's" is the correct word to use.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
