### ISSUE TITLE
Redundant declaration

### ISSUE THREAD

**Issue by LiveGood** [learn-co-curriculum/javascript-intro-to-looping#74]
Line 33 in "loops-test.js" is a redundant declaration that is not used anywehere after declaration.
`  const testArray = strangeArray.slice(array.length)`

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
