### ISSUE TITLE
not able to run the tests

### ISSUE THREAD

**Issue by deniznida** [learn-co-curriculum/javascript-intro-to-looping#9]
hey @pletcher, a student and I were not able to run the tests https://github.com/learn-co-students/javascript-intro-to-looping-v-000/issues/1

I tried to fix it, but then the solution would not pass. the error is happening in line 31 and 59 in the loops-test.js `const [array, t] = makeArray()`. error message from my jslint is 'const' is available in ES6.

**Comment by pletcher** [comment]
Hey Deniz,

What version of Node does the student have installed? (Needs to be a recent
version -- either 5 or 6 should work.)

Make sure the Learn gem is up to date, too. (`learn-test` needs to be at
least v2.3.0.)

Then these tests should run with `learn` without problems :)

**Comment by deniznida** [comment]
Not sure about the student, but my node version is `5.10.1` and learn-test `2.3.1` and I can't run the test

**Comment by pletcher** [comment]
What is the error? Is learn-test using the Mocha strategy?

Might need to bump to Node 6.0.0 if it keeps failing.

Do you use n? (https://github.com/tj/n)

**Comment by deniznida** [comment]
the error message is above. I'll try to upgrade to 6.0.0 and I have no idea if I'm using n. should I?

**Comment by deniznida** [comment]
I updated node to `v6.1.0` and it is working now, thanks!

**Comment by deniznida** [comment]
Do you want to add a note to the readme? Some students might have the same issue

**Comment by pletcher** [comment]
Sure, I'll add a note -- thanks for helping to troubleshoot!

**Comment by pletcher** [comment]
Also, sorry about the error message question -- I didn't see the screen grab in the email :)

**Comment by pletcher** [comment]
Closed with https://github.com/learn-co-curriculum/javascript-intro-to-looping/commit/9238df9531af7de999d1227b372ad88d12ac895b
